[package]
name = "hyperbitbit"
version = "0.0.1"
authors = ["Nikolay Novik <nickolainovik@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.7.0"
